# Generated by Django 4.0.4 on 2022-08-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Writer',
        ),
    ]
