# Generated by Django 4.0.4 on 2022-08-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_author_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writer',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
